AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppInstanceTypeParameter:
    Type: String
    Default: t2.micro
  InfraInstanceTypeParameter:
    Type: String
    Default: t2.medium
  WorkstationIp:
    Type: String
    Description: The IP address of the workstation that can RDP into the instance.
  AMI:
    Type: String
    Default: ami-0b4577d77dac11b84 
  Key:
    Type: String
    Description: The key used to access the instance.
Resources:
  IfraInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "prequel security group"
      GroupDescription: "SG for the prequel infrastructure"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:  20.188.245.156/32 
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp:  20.188.245.156/32
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp:  20.188.245.156/32 
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp:  20.188.245.156/32
          IpProtocol: tcp
          FromPort: '8085'
          ToPort: '8085'
          CidrIp:  20.188.245.156/32
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  AppInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "prequel security group"
      GroupDescription: "SG for the prequel infrastructure"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp:  20.188.245.156/32 
        - IpProtocol: tcp
          FromPort: '8088'
          ToPort: '8088'
          CidrIp:  20.188.245.156/32
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  preqel-infrastructure:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: InfraInstanceTypeParameter
      KeyName: !Ref Key
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  preqel-staging:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: AppInstanceTypeParameter
      KeyName: !Ref Key
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  preqel-prod:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: AppInstanceTypeParameter
      KeyName: !Ref Key
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
Outputs:
  infrastructure-PublicIp:
    Value:
      Fn::GetAtt:
        - prequel-infrastructure
        - PublicIp
    Description: Server's PublicIp Address
  staging-PublicIp:
    Value:
      Fn::GetAtt:
        - prequel-staging
        - PublicIp
    Description: Server's PublicIp Address
  prod-PublicIp:
    Value:
      Fn::GetAtt:
        - prequel-prod
        - PublicIp
    Description: Server's PublicIp Address